# Generated by Django 4.2.6 on 2023-10-25 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pid", models.IntegerField()),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("memory_usage_mb", models.FloatField()),
                ("cpu_usage_percent", models.FloatField()),
                ("ppid", models.IntegerField()),
                (
                    "os_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processes",
                        to="core.ossnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("os", models.CharField(max_length=100)),
                ("processor", models.CharField(max_length=100)),
                ("num_cores", models.IntegerField()),
                ("num_threads", models.IntegerField()),
                ("ram_gb", models.FloatField()),
                ("available_ram_gb", models.FloatField()),
                ("used_ram_gb", models.FloatField()),
                ("storage_total_gb", models.FloatField()),
                ("storage_used_gb", models.FloatField()),
                ("storage_free_gb", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="SubProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pid", models.IntegerField()),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("ppid", models.IntegerField()),
                ("memory_usage_mb", models.FloatField()),
                ("cpu_usage_percent", models.FloatField()),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subprocesses",
                        to="core.process",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ossnapshot",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="os_snapshots",
                to="core.system",
            ),
        ),
    ]
